# Max Preview
# [[mgr.prepend_keymap]]
# on   = "T"
# run  = "plugin max-preview"
# desc = "Maximize or restore preview"

# Open shell
[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

# Smart filter
[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

# Tags
# [[mgr.prepend_keymap]]
# on   = [ "b", "a" ]
# run  = 'plugin mactag --args="add"'
# desc = "Tag selected files"
#
# [[mgr.prepend_keymap]]
# on   = [ "b", "r" ]
# run  = 'plugin mactag --args="remove"'
# desc = "Untag selected files"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"
