[manager]
ratio          = [ 1, 4, 3 ]
show_hidden    = true
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
linemode = "size_and_mtime"
show_symlink = true
title_format   = "ヤズ: {cwd}"
SHELL = "fish"

[preview]
max_width       = 3840
max_height      = 2160
image_quality = 90

[pick]
open_title  = "で開く:"

[opener]
xld = [
    { run = 'xld "$@"', desc = "XLD" },
]

[open]
prepend_rules = [
	{ name = "*.cue", use = [ "open", "xld", "edit" ] },
]

[plugin]
prepend_preloaders = [
    { mime = "image/vnd.adobe.photoshop", run = "sips-preview" }
]
prepend_previewers = [
    { mime = "image/vnd.adobe.photoshop", run = "sips-preview" },
]

[[plugin.prepend_fetchers]]
id   = "mactag"
name = "*"
run  = "mactag"

[[plugin.prepend_fetchers]]
id   = "mactag"
name = "*/"
run  = "mactag"
