issuesSections:
  - title: 󱥒  Assigned
    filters: is:open assignee:@me
  - title: My Issues
    filters: is:open author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 100
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: issues
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
        hidden: true
      creator:
        width: 20
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings: {}
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: false
      compact: true
  colors:
    text:
      primary: "#a8c7fa"
      secondary: "#ff00ff"
      inverted: "#191726"
      faint: "#9fb6e9"
      warning: "#f97e72"
      success: "#72f1b8"
    background:
      selected: "#640fda"
    border:
      primary: "#03edf9"
      secondary: "#00ffff"
      faint: "#191726"
    inline:
      icons:
        newcontributor: "077"
        contributor: "075"
        collaborator: "178"
        member: "178"
        owner: "178"
        unknownrole: "178"
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
